### ISSUE TITLE
Windows setup instructions

### ISSUE THREAD

**Issue by appoll** [code4romania/catalog-data-chambers#27]
Tocmai am setat si rulat proiectul pe windows. dacă sunt info de interes, le pot adăuga.

**Comment by appoll** [comment]
just in case, pull request #28

**Comment by razvanpavel** [comment]
@appoll salutari! multumim! si ma bucur ca ti-a mers si te intereseaza proiectul nostru. mai exista alte repo-uri care se ocupa de datele generate de scraper si de un API cu Django REST, daca esti interesant imi poti lasa o adresa de mail si te invit in organizatie.

**Comment by appoll** [comment]
s-a intamplat să folosesc un setup foarte similar într-un proiect curent și sunt cât de cât familiar cu tehnologiile pe care le folosiți. Iar cauza pică bine, deci ajut cu mare drag: paul.a...n@

**Comment by razvanpavel** [comment]
Invite sent.
